version: '3.8'
services:
  app:
    image: microservicec.azurecr.io/moderate
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4100:3100
    environment:
      RABBITMQSUB_HOST: 10.0.0.4
      RABBITMQSUB_PORT: 4201
      RABBITMQMOD_HOST: rabbitmq
      RABBITMQSUB_QN: SUBMITTED_JOKES
      RABBITMQMOD_QN: MODERATED_JOKES
      RABBITMQANA_QN: LOGGED_JOKES
      JOKE_APP: 10.0.0.8
    volumes:
      - backup:/app/backup
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    hostname: rabbitmq
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_USER: root
      RABBITMQ_PASS: root
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - 4101:5672
      - 4102:15672
    volumes:
      - rabbit-vol:/var/lib/rabbitmq

volumes:
  rabbit-vol:
    driver: local
  backup: